### PR TITLE
Add Shopware 6.5.7.0 and Shopware 6.5.7.1

### PR DESCRIPTION
**Pull request by M-arcus**

### CODE REVIEW

**Comment by boxblinkracer** [comment]
this looks absoluteley perfect by the way :)

**Comment by lodhik9** [comment]
Thank you so much.

**Comment by M-arcus** [comment]
The CircleCI tests are not succeeding for the dev:

- https://app.circleci.com/pipelines/github/dockware/dockware/469/workflows/0bcf76b1-cb26-486d-9b9e-bcf18ec30f5d/jobs/895
- https://app.circleci.com/pipelines/github/dockware/dockware/469/workflows/0bcf76b1-cb26-486d-9b9e-bcf18ec30f5d/jobs/897
- https://app.circleci.com/pipelines/github/dockware/dockware/470/workflows/7b91d77e-6688-4cef-825a-2ffba979951a/jobs/898
- https://app.circleci.com/pipelines/github/dockware/dockware/470/workflows/7b91d77e-6688-4cef-825a-2ffba979951a/jobs/901

There is no difference to the 6.5.6.1 version, except of course the version number. Is this related to this PR or an external issue?

**Comment by martinweinmayr** [comment]
im currently on i t to check that

**Comment by M-arcus** [comment]
There was an issue in the manifest.json. play -> dev

**Pull request merged**
